[package]
name = "pmj"
version = "0.1.0"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
rand_xoshiro = "0.1"

[dev-dependencies]
structopt = "0.2"
